langage: python
python: 
        - "3.6"
        - "3.7"
        - "3.8"
install:
        - pip install -r requirements.txt
script:
        - coverage run -m --source=./src pytest
before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
after_script:
        - coverage xml
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
