langage: python
python: 
        - "3.6"
        - "3.7"
        - "3.8"
install:
        - pip install -r requirements.txt
script:
        - coverage run -m --source=./src pytest
after_script:
        - coverage xml
